# Generated by Django 3.2.6 on 2021-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUrBill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='demo',
            name='url',
            field=models.URLField(default="'"),
        ),
    ]
