# Generated by Django 3.2.6 on 2021-09-01 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUrBill', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill_items',
            new_name='Billitems',
        ),
        migrations.AlterField(
            model_name='bill_no',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 13, 13, 51, 440369)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=958443),
        ),
    ]
