# Generated by Django 3.2.6 on 2021-08-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetUrBill', '0002_auto_20210828_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
