# Generated by Django 3.2.6 on 2021-09-04 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUrBill', '0002_auto_20210901_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_no',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 12, 5, 20, 378423)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=480281),
        ),
    ]
