# Generated by Django 3.2.6 on 2021-08-29 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GetUrBill', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_no',
            fields=[
                ('bill_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=50)),
                ('Address', models.TextField(default='')),
                ('GST', models.IntegerField(default=0)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bill_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('Final_price', models.IntegerField(default=0)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GetUrBill.bill_no')),
            ],
        ),
    ]
