# Generated by Django 3.2.6 on 2021-08-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GetUrBill', '0003_bill_items_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_no',
            name='GST',
        ),
    ]
